import { create } from 'zustand';
import type { AppState, LogEntry, Position } from './types.js';
import { config } from './config.js';

interface Store extends AppState {
  logs: LogEntry[];
  set: (partial: Partial<AppState>) => void;
  pushLog: (entry: LogEntry) => void;
}

const initialPositions: Position[] = [
  {
    id: 'ETH_HEDGE',
    symbol: 'ETH/USDT',
    side: 'SHORT',
    strategy: 'FUNDING-ARB-α',
    entry: 2630.0,
    qty: 2.0,
    mark: 2626.2,
    upnl: 7.6,
    upnlPct: 0.14,
    leverage: 1,
    marginType: 'ISOLATED',
    liqDistancePct: null,
    serverSl: '—',
    serverTp: 'fund',
    posType: 'SPOT+SHORT',
  },
  {
    id: 'SOL_HEDGE',
    symbol: 'SOL/USDT',
    side: 'SHORT',
    strategy: 'FUNDING-ARB-α',
    entry: 112.2,
    qty: 30.0,
    mark: 111.6,
    upnl: 18.0,
    upnlPct: 0.53,
    leverage: 1,
    marginType: 'ISOLATED',
    liqDistancePct: null,
    serverSl: '—',
    serverTp: 'fund',
    posType: 'SPOT+SHORT',
  },
  {
    id: 'BTC_ETH_PAIR',
    symbol: 'BTC/ETH',
    side: 'LONG',
    strategy: 'PAIRS-TRD-β',
    entry: 30.75,
    qty: 0.5,
    mark: 30.87,
    upnl: 60.0,
    upnlPct: 0.39,
    leverage: 2,
    marginType: 'ISOLATED',
    liqDistancePct: 14.2,
    serverSl: '29.5',
    serverTp: '32.0',
    posType: 'LONG/SHORT',
  },
  {
    id: 'SOL_AVAX_PAIR',
    symbol: 'SOL/AVAX',
    side: 'LONG',
    strategy: 'PAIRS-TRD-β',
    entry: 13.02,
    qty: 20.0,
    mark: 13.08,
    upnl: 12.0,
    upnlPct: 0.46,
    leverage: 2,
    marginType: 'ISOLATED',
    liqDistancePct: 12.8,
    serverSl: '12.4',
    serverTp: '13.8',
    posType: 'LONG/SHORT',
  },
  {
    id: 'BTC_MOM',
    symbol: 'BTC/USDT',
    side: 'LONG',
    strategy: 'MOMENTUM-γ',
    entry: 80950.0,
    qty: 0.3,
    mark: 81070.0,
    upnl: 36.0,
    upnlPct: 0.15,
    leverage: 3,
    marginType: 'ISOLATED',
    liqDistancePct: 18.7,
    serverSl: '79500',
    serverTp: '83500',
    posType: 'LONG',
  },
  {
    id: 'AVAX_MOM',
    symbol: 'AVAX/USDT',
    side: 'LONG',
    strategy: 'MOMENTUM-γ',
    entry: 8.48,
    qty: 100.0,
    mark: 8.54,
    upnl: 6.0,
    upnlPct: 0.71,
    leverage: 3,
    marginType: 'ISOLATED',
    liqDistancePct: 16.4,
    serverSl: '8.10',
    serverTp: '9.20',
    posType: 'LONG',
  },
];

export const useStore = create<Store>((set) => ({
  mode: config.mode,
  equity: 100_000,
  upnl: 139.6,
  marginUsed: 8420,
  positions: initialPositions,
  agents: [
    { id: 'FUNDING-ARB-α', status: 'RUNNING', strategy: 'funding_rate_carry', positions: 2, winRate: 98.2, pnl: 8420, progress: 92 },
    { id: 'PAIRS-TRD-β', status: 'RUNNING', strategy: 'stat_pairs_zscore', positions: 2, winRate: 71.4, pnl: 12840, progress: 68 },
    { id: 'MOMENTUM-γ', status: 'RUNNING', strategy: 'atr_vol_momentum', positions: 2, winRate: 64.8, pnl: 6210, progress: 54 },
    { id: 'RISK-MGR-δ', status: 'WATCHING', strategy: 'liq_guard_isolated', positions: 0, winRate: 100, pnl: 0, progress: 42 },
    { id: 'EXECUTOR-ε', status: 'RUNNING', strategy: 'binance_router', positions: 0, winRate: 100, pnl: 0, progress: 95 },
  ],
  logs: [
    { ts: Date.now() - 3000, agent: 'MANUAL', msg: 'Close ETH/USDT SPOT+SHORT → market close via Binance API', level: 'info' },
    { ts: Date.now() - 6000, agent: 'SYSTEM', msg: 'Orchestrator started in PAPER mode', level: 'info' },
  ],
  funding: { BTCUSDT: 0.0001, ETHUSDT: 0.0001, SOLUSDT: 0.0001, AVAXUSDT: 0.0001 },
  spotPrices: {
    BTC: { price: 81070.0, changePct: 4.27 },
    ETH: { price: 2626.2, changePct: 5.55 },
    SOL: { price: 111.6, changePct: 5.51 },
    AVAX: { price: 8.54, changePct: 7.63 },
  },
  strategyMetrics: {
    fundingEthRate: 0.0001,
    fundingEthApr: 10.95,
    fundingSolRate: 0.0001,
    fundingSolApr: 10.95,
    nextFundingCountdown: '7h58m',
    zscoreBtcEth: -0.74,
    zscoreSolAvax: -1.38,
    btcAtr: 107.0,
    avaxAtr: 0.07,
  },
  todayDecisions: 142,
  todayExecuted: 98,
  todayMonitored: 32,
  successRate: 96.4,
  totalPnl: 27766,
  sharpe: 2.84,
  maxDd: -2.4,
  liqEvents: 0,
  apiWeight: 247,
  var95: -1842,
  exposurePct: 42,
  liqBufferAtr: 18.7,
  corrBtcEth: 0.91,
  serverTime: Date.now(),
  set: (partial) => set((state) => ({ ...state, ...partial })),
  pushLog: (entry) => set((state) => ({ logs: [entry, ...state.logs].slice(0, 50) })),
}));
